#!/bin/sh
#	
#	@(#)sendcap	1.4	96/02/27 11:52:41
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#
#	Send a new Amoeba user the .capability file needed to access Amoeba
#	from Unix.
#

case $# in
1)	AM_NAME=$1
	UN_NAME=$1
	;;
2)	AM_NAME=$1
	UN_NAME=$2
	;;
*)	echo "Usage: $0 amoeba-login-name [ unix-login-name ]"
	exit 1
	;;
esac
	
if [ X$MAILER = X ]
then
	MAILER=/usr/lib/sendmail
	MAILFLAGS=-t
fi

TMPFILE1=/tmp/sendcap$$_1
WHOAMI=`whoami`

trap "/bin/rm -f $TMPFILE1" 0 1 2 3 15

get /super/users/$AM_NAME | dd bs=1 skip=4 count=16 >$TMPFILE1 2>/dev/null
if [ $? -ne 0 ]
then
	exit 1
fi
chmod 400 $TMPFILE1

( echo "To: $UN_NAME
From: $WHOAMI
Subject: Your Amoeba .capability file

Dear $UN_NAME,

	Below you will find the uuencoded version of your .capability file.
You should pass this entire mail message through the command uudecode in
your home directory.  It will create a file called .capability.  Make sure
that it is read only for you (mode 400).  After this you should be able to
execute commands under Unix that talk to the Amoeba system (if there is an
Amoeba driver in your Unix kernel and your PATH is set correctly).

					$WHOAMI

"
uuencode $TMPFILE1 .capability

) | $MAILER $MAILFLAGS

exit 0
