#!/bin/sh
#	
#	@(#)amcincl	1.3	96/02/27 11:56:51
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

if [ $# -eq 0 ]; then
	set - "-?"
fi
myname="$0"
verbose=0
cc_flags=""
CC=${CC:-cc}
while [ $# -gt 0 ] ; do
	case "$1" in
	-myname)shift	# So that amcincl can have its name appear in errors
		myname="$1" ;;
	-v)	verbose=1 ;;
	-CC)	shift
		CC="$1"	# Allows alternative cc to be specified
		;;
	"-?"|-o|-c)
		cat 1>&2 <<EOF
Usage: $myname [ -v ] [ -Iinclude-dir ]...  C-file...

Runs cpp on the C-files and prints tree of nested include file names.
With -v, also prints pre-processed contents of the C-files and include files.
EOF
		exit 1 ;;
	-*)	cc_flags="$cc_flags $1" ;;
	*)	break ;;
	esac
	shift
done
$CC -E $cc_flags "$@" |
	awk 'BEGIN	  {	prev_line_blank = 0
				level = 0
			  }
	    /^#.*[0-9]$/  {
				if ($4 == 1) {
					for (i=0; i<level; i++)
						printf("	")
					if ('$verbose')
						printf("#include %s\n", $3)
					else
						printf("%s\n", \
						    substr($3, 2, length($3)-2))
					name[level] = $3
					level = level + 1
					prev_line_blank = 0
				} else if ($4 == 2) {
					level = level - 1
					if ('$verbose') {
						for (i=0; i<level; i++)
							printf("	")
						print "#endinclude " \
								name[level] "\n"
						prev_line_blank = 1
					} else
						prev_line_blank = 0
				}
				next
			  }
	    /^#/	  {	next
			  }
	    /^[ 	]*$/ {	if ('$verbose' && !prev_line_blank)
					print $0
				prev_line_blank = 1
				next
			  }
		    	  {	if ('$verbose') {
					for (i=0; i<level; i++)
						printf("	")
					printf ("%s\n", \
						    substr($0, 1, 79 - 8*level))
					prev_line_blank = 0
				}
				next
			  }'
