#! /bin/sh
#	
#	@(#)amdumptree	1.3	94/04/07 14:09:45
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

# amdumptree: copy a unix tree to amoeba
# Find is not sufficient, because it doesn't follow symlinks.
# The dump scripts also take care of the possibility that the destination
# files/directories already exist.  Otherwise everything would have to be
# recompiled when, e.g., the header files are re-installed.
#
# Note that no backup of files to .old is done if the -n option is specified.

PROG=$0
nobackup=

case $1 in
-n)
    nobackup="-n"
    shift
    ;;
esac

if [ $# -ne 2 ]
then
    echo usage: $PROG [-n] unixdir amoebadir 2>&1
    exit 1
fi

# echo $PROG $1 $2

unixdir=$1
amdir=$2
or=-o

cd $unixdir

# recursively dump the tree, but skip RCS entries 
find .  \( -name RCS $or -name SCCS -prune -exec echo skip {}	\; \) \
    $or \( -name Markfile -exec echo skip {}			\; \) \
    $or \( -type l -exec amdumpsym $unixdir {} $amdir 		\; \) \
    $or \( -type d -exec amdumpdir {} $amdir 			\; \) \
    $or \( -exec amdumpfile $nobackup {} $amdir 		\; \)

