/*	@(#)cmos.init	1.3	94/04/06 09:17:29 */
/*
 * Copyright 1994 Vrije Universiteit, The Netherlands.
 * For full copyright and restrictions on use see the file COPYRIGHT in the
 * top level of the Amoeba distribution.
 */

/*
 * cmos.init
 *
 * Cmos must be initialized before MM, since MM uses it to determine the
 * amount of memory installed. On the fly it also generates some bits for
 * the random generator seed.
 */
cmos_init initmm
cmos_init initrand
THREADS cmos_initthreads
