/*	@(#)floppy.init	1.3	94/04/06 09:19:15 */
/*
 * Copyright 1994 Vrije Universiteit, The Netherlands.
 * For full copyright and restrictions on use see the file COPYRIGHT in the
 * top level of the Amoeba distribution.
 */

/*
 * floppy.init
 *
 * The floppy is initialized before the virtual disk server since the
 * ramdisk loader might want to initialize itself by reading the contents
 * from a floppy disk. The ramdisk has to be first in so that the bullet
 * server will test it first for a valid file system.
 */
THREADS flp_startup
flp_startup initvirdisk
