#!/bin/sh
#	
#	@(#)do_gld	1.3	94/04/05 17:08:48
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

FILES=
OUTPUT=
OPTS="-n"
ARCH=sparc
KERNEL=no
UNIX=no
GNUBIN=
SOFTFP=no
LIBMATH=no

# Parse options
while [ $# -gt 0 ]
do
        case $1 in
        -o)     	OUTPUT=$2; OPTS="$OPTS -o $2"; shift ;;
	-G)		GNUBIN=$2; shift ;;
	-kernel)	KERNEL=yes ;;
        -mam_i80386)	ARCH=i80386 ;;
        -mam_mc68000)	ARCH=mc68000 ;;
        -mam_sparc)	ARCH=sparc ;;
        -mam_*)		echo "architecture $1 not supported" >&2; exit 1 ;;
	-unix)		UNIX=yes ;;
        -T*)    	OPTS="$1 $2 $OPTS"; shift ;;
	-lsoft)		SOFTFP=yes;;
	-lm)		LIBMATH=yes;;
	-e)		OPTS="$OPTS $1 $2"; shift ;;
        -[Ll]*)		FILES="$FILES $1" ;;	# not in OPTS; order important
	-O|-sun4)	;;			# ignore these ones
        -*)     	OPTS="$OPTS $1" ;;	# also accept all other options
        *.[oa])		FILES="$FILES $1" ;;
        *)		echo "unrecognized argument $1" >&2; exit 1;;
        esac
        shift
done

# If not specified, use default for GNUBIN.
if [ "X$GNUBIN" = X ]
then
	GNUBIN=`amdir`/bin.`arch`/gnu
fi

# Override the INPUTFORMAT flag in case the gnu loader recognizes the wrong
# objectfile/library format
INPUTFORMAT=""

# Specify LDEMULATION to get the right output format:
case $ARCH in
i80386)
	if [ $KERNEL = yes ]
	then
		LDEMULATION=am_i386kaout
	else
		LDEMULATION=am_i386aout
	fi
	;;
*)	LDEMULATION=am_"$ARCH"aout
	;;
esac
export LDEMULATION

if [ $SOFTFP = yes ]
then
	FILES="$FILES $GNUBIN/$ARCH/floatlib.o"
fi
# ignore LIBMATH; the math library for the conf tree should be used.

# do the linking
$GNUBIN/ld $INPUTFORMAT $OPTS $FILES
exitval=$?

exit $exitval
