#!/bin/sh
#	
#	@(#)do_ld	1.4	96/02/16 15:57:57
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

FILES=
OUTPUT="a.out"
OPTS="-n"
ACVOPTS=""
ARCH=i80386	# default
KERNEL=no
UNIX=no
GNULIB=
SOFTFP=no
LIBMATH=no
LIBGCC=no
LIBES=""

# Parse options
while [ $# -gt 0 ]
do
        case $1 in
        -o)     	OUTPUT=$2; shift ;;
	-G)		GNULIB=$2; shift ;;
	-kernel)	KERNEL=yes ;;
        -mam_i80386)	ARCH=i80386 ;;
        -mam_mc68000)	ARCH=mc68000 ;;
        -mam_sparc)	ARCH=sparc ;;
        -mam_*)		echo "architecture $1 not supported" >&2; exit 1 ;;
	-unix)		UNIX=yes ;;
        -T*)    	OPTS="$1 $2 $OPTS"; shift ;;
	-[lm]soft)	SOFTFP=yes;;
	-lhwfp)		SOFTFP=no;;
	-lgcc)		LIBGCC=yes;;
	-l*|*.a)	LIBES="$LIBES $1";;
	-s)		ACVOPTS="$ACVOPTS $1 $2"; shift;;
	-[DOU]*|-sun4)	;;			# ignore these ones
        -*)     	OPTS="$OPTS $1" ;;	# also accept all other options
        *.o)		FILES="$FILES $1" ;;
        *)		echo "unrecognized argument $1" >&2; exit 1;;
        esac
        shift
done

# If not specified, use default for GNULIB.
if [ "X$GNULIB" = X ]
then
	GNULIB=`amdir`/bin.`arch`/gnu
fi

# Override the INPUTFORMAT flag in case the gnu loader recognizes the wrong
# objectfile/library format
INPUTFORMAT=""

# Specify LDEMULATION to get the right output format:
case $ARCH in
i80386)
	if [ $KERNEL = yes ]
	then
		LDEMULATION=am_i386kaout
	else
		LDEMULATION=am_i386aout
	fi
	;;
*)	LDEMULATION=am_"$ARCH"aout
	;;
esac
export LDEMULATION

if [ $SOFTFP = yes ]
then
	FILES="$FILES $GNULIB/$ARCH/floatlib.o"
fi

# do the linking
$GNULIB/ld -L$GNULIB/$ARCH $INPUTFORMAT $OPTS -o $OUTPUT $FILES $LIBES
exitval=$?

exit $exitval
