/*	@(#)errlist.h	1.2	94/04/06 16:52:59 */
/*
 * Copyright 1994 Vrije Universiteit, The Netherlands.
 * For full copyright and restrictions on use see the file COPYRIGHT in the
 * top level of the Amoeba distribution.
 */

#ifndef __ERRLIST_H__
#define __ERRLIST_H__

char *sys_errlist[] = {
	"Error 0",
	"Operation not permitted",
	"No such file or directory",
	"No such process",
	"Interrupted system call",
	"Input/output error",
	"No such device or address",
	"Arg list too long",
	"Exec format error",
	"Bad file descriptor",
	"No child processes",
	"Resource temporarily unavailable",
	"Not enough core",
	"Permission denied",
	"Bad address",
	"Error 15",
	"Resource busy",
	"File exists",
	"Error 18",
	"No such device",
	"Not a directory",
	"Is a directory",
	"Invalid argument",
	"Too many open files in system",
	"Too many open files",
	"Inappropriate ioctl operation",
	"Error 26",
	"File too large",
	"No space left on device",
	"Invalid seek",
	"Read-only file system",
	"Too many links",
	"Broken pipe",
	"Domain error",
	"Result too large",
	"Operation would block",
	"Error 36",
	"Error 37",
	"Error 38",
	"Error 39",
	"Error 40",
	"Error 41",
	"Error 42",
	"Error 43",
	"Error 44",
	"Error 45",
	"Error 46",
	"Error 47",
	"Error 48",
	"Error 49",
	"Error 50",
	"Error 51",
	"Error 52",
	"Error 53",
	"Error 54",
	"Error 55",
	"Error 56",
	"Error 57",
	"Error 58",
	"Error 59",
	"Error 60",
	"Error 61",
	"Error 62",
	"File name too long",
	"Error 64",
	"Error 65",
	"Directory not empty",
	"Error 67",
	"Error 68",
	"Error 69",
	"Error 70",
	"Error 71",
	"Error 72",
	"Error 73",
	"Error 74",
	"Error 75",
	"Error 76",
	"Error 77",
	"Error 78",
	"Error 79",
	"No locks available",
	"Function not implemented",
};

int sys_nerr = 82;

#endif /* __ERRLIST_H__ */
