/*	@(#)param.h	1.2	94/04/06 11:34:51 */
/*
 * Copyright 1994 Vrije Universiteit, The Netherlands.
 * For full copyright and restrictions on use see the file COPYRIGHT in the
 * top level of the Amoeba distribution.
 */

/*
 * Tunable parameters
 */

/*
 * Address at which the program image is loaded.
 */
#define	LOADADDR	0x002000
#define LOADSEG		0x000200

/*
 * Size of the ROM image (16 Kb)
 */
#define	ROMSIZE		0x4000

/*
 * Location in RAM where a copy of the program's
 * data segment is placed (640Kb - 32Kb)
 */
#define	RAMSIZE		0x8000
#define	RAMADDR		0x98000
#define	RAMSEG		0x09800

/*
 * RARP as well as TFTP uses a timeout mechanism which starts with four
 * seconds and eventually go up as high as 4 << NRETRIES seconds. That
 * is, the number of retry iterations.
 */
#define	NRETRIES	6

#ifdef MONITOR
/*
 * BIOS break interrupt. This interrupt is generated by the
 * keyboard driver every time CTRL BREAK is pressed. We pick
 * it up to jump into the monitor.
 */
#define	BRK_INTR	0x1B

/*
 * Number of arguments in the users' command line
 */
#define	ARGVECSIZE	5
#endif /* MONITOR */
