#!/bin/sh
if [ ! -f DeleteFiles.sh ]; then
    echo OOPS! You are running DeleteFiles.sh in the wrong directory!
    exit 1
fi
rm -f ./conf/amoeba/SCCS
rm -f ./conf/amoeba/Makefile.com
rm -f ./conf/amoeba/Makefile.lib
rm -f ./conf/amoeba/Makefile.src
rm -f ./conf/amoeba/chan.c
rm -f ./conf/amoeba/conf.c
rm -f ./conf/amoeba/conf.h
rm -f ./conf/amoeba/conf_dial.c
rm -f ./conf/amoeba/d_lock.h
rm -f ./conf/amoeba/msgtailor.c
rm -f ./conf/amoeba/s_tailor.c
rm -f ./conf/amoeba/s_tailor.h
rm -f ./conf/SCCS
rm -f ./conf/sitesetup
rm -f ./h/SCCS
rm -f ./h/deliversvr.h
rm -f ./h/smtpsrvr.h
rm -f ./h/util.h
rm -f ./lib/addr/SCCS
rm -f ./lib/addr/Makefile.real
rm -f ./lib/addr/ap_1adr.c
rm -f ./lib/addr/ghost.c
rm -f ./lib/addr/parse.c
rm -f ./lib/mmdf/SCCS
rm -f ./lib/mmdf/Makefile.real
rm -f ./lib/mmdf/interrupt.c
rm -f ./lib/mmdf/ml_send.c
rm -f ./lib/mmdf/mm_io.c
rm -f ./lib/mmdf/mq_rdmail.c
rm -f ./lib/mmdf/qu_io.c
rm -f ./lib/table/SCCS
rm -f ./lib/table/Makefile.real
rm -f ./lib/table/tb_io.c
rm -f ./lib/util/SCCS
rm -f ./lib/util/Makefile.real
rm -f ./lib/util/gpwlnam.c
rm -f ./lib/util/lk_lock.c
rm -f ./lib/util/whoami.c
rm -f ./lib/util/creatdir.c
rm -f ./lib/util/ll_log.c
rm -f ./lib/SCCS
rm -f ./lib/Makefile
rm -f ./mmtailor/SCCS
rm -f ./mmtailor/mmdftailor
rm -f ./src/delay/SCCS
rm -f ./src/delay/Makefile.real
rm -f ./src/deliver/SCCS
rm -f ./src/deliver/Makefile.real
rm -f ./src/deliver/ch_io.c
rm -f ./src/deliver/deliverguts.c
rm -f ./src/deliver/delivert.c
rm -f ./src/deliver/threaded.c
rm -f ./src/list/SCCS
rm -f ./src/list/Makefile.real
rm -f ./src/local/SCCS
rm -f ./src/local/Makefile.real
rm -f ./src/local/ch_local.c
rm -f ./src/local/qu2lo_send.c
rm -f ./src/local/lo_wtmail.c
rm -f ./src/smtp/SCCS
rm -f ./src/smtp/Makefile.real
rm -f ./src/smtp/sm_wtmail.c
rm -f ./src/smtp/smtpd.c
rm -f ./src/smtp/smtpsrvr.c
rm -f ./src/smtp/tcp.am.c
rm -f ./src/submit/SCCS
rm -f ./src/submit/Makefile.real
rm -f ./src/submit/mq_wtmail.c
rm -f ./src/submit/submit.c
rm -f ./src/tools/SCCS
rm -f ./src/tools/Makefile.real
rm -f ./src/tools/setup.c
rm -f ./src/tools/mailid.c
rm -f ./src/SCCS
rm -f ./src/Makefile
rm -f ./uip/msg/SCCS
rm -f ./uip/msg/Makefile.real
rm -f ./uip/msg/msg.h
rm -f ./uip/msg/msg1.c
rm -f ./uip/msg/msg2.c
rm -f ./uip/msg/msg3.c
rm -f ./uip/msg/msg4.c
rm -f ./uip/msg/msg5.c
rm -f ./uip/other/SCCS
rm -f ./uip/other/Makefile.real
rm -f ./uip/other/checkmail.c
rm -f ./uip/other/newmail.c
rm -f ./uip/other/rcvtrip.c
rm -f ./uip/other/resend.c
rm -f ./uip/other/v6mail.c
rm -f ./uip/other/emactovi.c
rm -f ./uip/other/sendmail.c
rm -f ./uip/send/SCCS
rm -f ./uip/send/Makefile.real
rm -f ./uip/send/s_drfile.c
rm -f ./uip/send/s_get.c
rm -f ./uip/snd/SCCS
rm -f ./uip/snd/Makefile.real
rm -f ./uip/snd/s_input.c
rm -f ./uip/snd/s_main.c
rm -f ./uip/snd/s_onint.c
rm -f ./uip/snd/alias.c
rm -f ./uip/snd/mkversion
rm -f ./uip/snd/s_get.c
rm -f ./uip/SCCS
rm -f ./uip/Makefile
rm -f ./SCCS
rm -f ./Makefile
rm -f ./MkDelFiles.sh
rm -f ./README.AMOEBA
rm -f ./DeleteFiles.sh
