#!/bin/sh
#	
#	@(#)amdir	1.3	96/02/27 13:12:21
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#  This script prints the name of the root of the amoeba development tree.
#  It should be adjusted to suit each local site.
#
echo "/profile/module/amoeba"
