#!/bin/sh
#	
#	@(#)chmod	1.2	94/04/07 15:58:29
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

echo cannot chmod $*, use chm instead
exit 0
