#!/bin/sh
#	
#	@(#)hostname	1.3	96/02/27 13:12:27
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

cat /etc/Hostname
