#!/bin/sh
#	
#	@(#)makeproto	1.3	94/04/07 15:58:50
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#mkproto $* | egrep -v '(PRIVATE|LOCAL)' | sed "s/PUBLIC/EXTERN/"
mkproto $* | grep -v PRIVATE | grep -v LOCAL | sed "s/PUBLIC/EXTERN/"
