#!/bin/sh
#	
#	@(#)monpool	1.3	96/02/27 13:12:34
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#
#	Monpool
#	Let's you keep a running watch on the status of pool processors
#
DELAY=5
ERR=false

while [ $# -gt 0 ]
do
	case $1 in
	-p)
		shift
		if [ $# -le 0 ]
		then
			ERR=true
			break
		fi
		POOLDIR=$1
		DIRSTAT=`std_info $POOLDIR 2> /dev/null`
		case $DIRSTAT in
		/*)
			;;
		*)
			echo "$0: cannot find pool directory: $POOLDIR"
			exit 2
		esac
		shift ;;

	[0-9]*)
		DELAY=$1
		shift ;;

	*)
		ERR=true
		break ;;
	esac
done

if [ $ERR = true ]
then
	echo "Usage: $0 [-p pooldir] [delay]" >&2
	echo "default pool directory is /profile/pool" >&2
	echo "default delay is 5 seconds" >&2
	exit 1
fi

EXINIT=""
while :; do echo '!Gaps -al 3' $POOLDIR; sleep $DELAY ; done | elvis
