#!/bin/sh
#	
#	@(#)spell	1.3	94/04/07 15:59:24
#
# Copyright 1994 Vrije Universiteit and Stichting Mathematisch Centrum,
# The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

cat $* | prep | sort -u | comm -23 - /usr/lib/dictionary
