#!/bin/sh
#	
#	@(#)touch	1.3	94/04/07 15:59:33
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.


prog=`basename $0`
cflag=false
files=""

if [ $# -lt 1 ]
then
	echo "usage: touch [-c] file ..." 2>&1
	exit 1
fi

# handle arguments
for f
do
	case $f in
	-c)	cflag=true;;
	*)	files="$files $f";;
	esac
done

# touch the files by appending nothing to them
for f in $files
do
	finfo=`c2a $f 2>/dev/null`
	case $finfo in
	*\(FF\)*)
	    # We have an owner cap so we should be able to touch it
	    # if the directory is writable.
	    getdelput $f $f
	    ;;
	*)
	    # see if it exists
	    if std_info $f > /dev/null 2>&1
	    then
		# yes it exists but we don't have an owner cap!
		echo $prog: touch of $f failed
	    else
		if $cflag
		then
		    echo $prog: $f does not exist
		else
		    echo -n >> $f
		fi
	    fi
	    ;;
	esac
done

exit 0

