#!/bin/sh
#	
#	@(#)bstatus	1.3	94/04/06 11:54:10
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#	bstatus [server_name]
BULLROOT=/profile/cap/bulletsvr

case $# in
0)  name=$BULLROOT/default
    ;;
1)  case $1 in
    /*|\./*) name=$1 ;;
    *) name=$BULLROOT/$1 ;;
    esac
    ;;
*)  echo "Usage: $0 [server_name]"
    exit 1
    ;;
esac

std_status $name
