#!/bin/sh
#	
#	@(#)buildlibs	1.6	96/02/27 10:19:35
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#
#	Buildlibs (June 1990)
#
#	This program goes into the specified configuration directory
#	(default is .) and attempts to build all the libraries.
#
# Assuming that build.domake is in the same directory as this script, convert
# $0 to a valid build.domake command:
#
CFNAME=Amakefile
MYDIRNAME=`expr $0 : '\(.*\)/.*'`
if [ X$MYDIRNAME != X ]
then
	MYDIRNAME=$MYDIRNAME/
fi
case $MYDIRNAME in
/*)	;;
*)	MYDIRNAME=`pwd`/$MYDIRNAME ;;
esac
DOMAKE=${MYDIRNAME}build.domake
PROG=`basename $0`
if [ $# -gt 1 ]
then
	echo "Usage: $PROG [ <config directory> ]"
	exit 1
fi
if [ $# -eq 1 ]
then
	if [ ! -d $1 ]
	then
		echo $PROG: directory \`$1\' not found!
		exit 1;
	fi
	cd $1
fi
#
#  First build the libraries which are needed to make everything else.
#
if [ ! -d lib ]
then
	echo "$PROG: doesn't look like an amoeba configuration tree"
	echo "bye bye"
	exit 1
fi
find lib -name $CFNAME -exec $DOMAKE {} \;
exit $?
