#!/bin/sh
#	
#	@(#)chkbuild	1.1	96/02/27 10:19:41
#
# Copyright 1995 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

if [ $# -ne 1 ]
then
    echo Usage: $0 build.out
    exit 1
fi
PAGER=${PAGER:-yap}
egrep -v '^\[|possible pointer al|# .*:$|all done' $1 | $PAGER
