#!/bin/sh
#	
#	@(#)localumask	1.2	94/04/06 11:55:20
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#
#  This command sets the umask for building the configuration trees.
#  It can be empty to leave it at the user's choice or set to the needs
#  of a particular group.

umask 2
