#!/bin/sh
#	
#	@(#)makeversion	1.3	96/02/27 10:20:27
#
# Copyright 1994 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

#   Generate a version file for the amoeba kernel with name specified by $1
#   The filename had better end in a .o if you want a predictable result from
#   make programs.
#	The environment variables CC & CFLAGS determine the compilation of
#	the .c file.
#	The environment variable COMPILER_SET should be set before calling
#	this if it is important in the string
#
if [ $# -ne 1 -o "$1" = "" ]
then
	echo "Usage: $0 filename"
	exit 1
else
	VFILE=$1
fi

CC=${CC-cc}
VFILE=`basename $VFILE .o`.c
if [ ! -f $VFILE ]
then
	VERSION='"0"'
else
	VERSION=`cat $VFILE`
fi
VERSION=`expr "$VERSION" : '.*"\([0-9][0-9]*\).*"' `
VERSION=`expr $VERSION + 1`
if sh -c 'hostname' >/dev/null 2>&1
then HOST=`hostname`
else HOST=`uname -n`
fi
if [ "X$USER" = X ]
then
	if [ "X$LOGNAME" = X ]
	then	USER=unknown
	else	USER="$LOGNAME"
	fi
fi
DATE=`date`
CURDIR=`pwd`
if (echo '\n' | grep n >/dev/null); then
    STRING="$VERSION <$COMPILER_SET> by $USER@$HOST ($DATE)\nin directory $CURDIR"
else
    STRING="$VERSION <$COMPILER_SET> by $USER@$HOST ($DATE)\\\\nin directory $CURDIR"
fi
echo "char version[] = \"$STRING\";" > $VFILE
$CC -c $CFLAGS $VFILE
