#!/bin/sh
#	
#	@(#)reserve_svr	1.1	96/02/27 10:20:52
#
# Copyright 1995 Vrije Universiteit, The Netherlands.
# For full copyright and restrictions on use see the file COPYRIGHT in the
# top level of the Amoeba distribution.

PYTHONDIR=/super/module/python
PYTHONPATH="$PYTHONDIR/amlib:$PYTHONDIR/lib"
export PYTHONPATH
if [ $# -eq 0 ]
then
	$PYTHONDIR/util/reserver.py
else
	$PYTHONDIR/util/reserver.py "$@"
fi
exit 0
