/*	@(#)disp_pdisks.c	1.4	96/02/27 10:12:18 */
/*
 * Copyright 1994 Vrije Universiteit, The Netherlands.
 * For full copyright and restrictions on use see the file COPYRIGHT in the
 * top level of the Amoeba distribution.
 */

/*
 * display_pdisks
 *
 *	Prints the linked list of available disks generated by find_disks().
 */

#include "amoeba.h"
#include "module/disk.h"
#include "vdisk/disklabel.h"
#include "dsktab.h"
#include "menu.h"
#include "proto.h"

extern dsktab *	Pdtab;
extern char *	Hostname;
extern int	Host_os;
extern struct menu	Host_os_menu[];


void
display_pdisks _ARGS(( void ))
{
    dsktab *	p;	/* pointer to table */
    int		i;	/* number of entry */
    int		warn;

    printf("\n  Physical disks available on host ``%s''\n", Hostname);
    printf("  No. Name\tSize (in sectors)\t Label type\n");
    warn = 0;
    for (i = 0, p = Pdtab; p != 0; i++, p = p->next)
    {
	printf("%4d: %s\t %10d\t\t  ", i, p->name, p->size);
	if (p->labelled == NO_LABEL)
	    printf("None\n");
	else
	{
	    printf("%s\n", Host_os_menu[p->labelled].m_text);
	    if (p->labelled != Host_os)
		warn = 1;
	}
    }
    if (warn)
	printf("\nWARNING: some disks have labels from other operating systems!!\n");
}


void
menu_display_pdisks _ARGS(( void ))
{
    display_pdisks();
    pause();
}
